font_family JetBrainsMono Nerd Font
font_size 14.0
window_padding_width 10
window_margin_width 4
background_opacity 0.8
confirm_os_window_close 0
cursor_shape beam
cursor_blink_interval 0.5
enable_audio_bell no

foreground #e6dcff
background #0d0d0d
selection_foreground #0d0d0d
selection_background #00ffff
cursor #00ffff
cursor_text_color #0d0d0d

color0  #151515
color1  #ff5c8a
color2  #50fa7b
color3  #f1fa8c
color4  #00ffff
color5  #bd93f9
color6  #8be9fd
color7  #f8f8f2
color8  #44475a
color9  #ff79c6
color10 #50fa7b
color11 #ffff80
color12 #00ffff
color13 #bd93f9
color14 #00f7ff
color15 #ffffff

active_border_color #00ffff
inactive_border_color #3b2a52
bell_border_color #bd93f9
